# Generated by Django 6.1 on 2026-09-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Описание товара',
                'verbose_name_plural': 'Описание товара',
                'ordering': ['-time_update'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ColorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='goods/color/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='SeasonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10, verbose_name='Сезон')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Сезон коллекции',
                'verbose_name_plural': 'Сезон коллекции',
            },
        ),
        migrations.CreateModel(
            name='SexCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10, verbose_name='Пол')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размер',
            },
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55, verbose_name='Тип')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Тип товара',
            },
        ),
        migrations.CreateModel(
            name='GoodsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('new_model', models.BooleanField(default=False, verbose_name='Новинка')),
                ('sale', models.BooleanField(default=False, verbose_name='Распродажа')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Цена')),
                ('new_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Новая цена')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.colorcategory', verbose_name='Цвет')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.abstractgoods', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Витрина',
                'verbose_name_plural': 'Витрина',
                'ordering': ('-time_update',),
            },
        ),
        migrations.CreateModel(
            name='ImagesGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/photo', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('represent_photo', models.BooleanField(default=False, verbose_name='Карточка товара')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goodscollection', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товара',
            },
        ),
        migrations.AddField(
            model_name='abstractgoods',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.seasoncategory', verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='abstractgoods',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.sexcategory', verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Артикул')),
                ('slug', models.SlugField(unique=True)),
                ('quantity', models.IntegerField(verbose_name='Остаток')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goodscollection', verbose_name='Название')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.sizecategory', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.AddField(
            model_name='abstractgoods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.typecategory', verbose_name='Тип'),
        ),
        migrations.AddIndex(
            model_name='goodscollection',
            index=models.Index(fields=['time_update'], name='goods_goods_time_up_c03b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractgoods',
            index=models.Index(fields=['-time_update'], name='goods_abstr_time_up_3ff81c_idx'),
        ),
    ]
